### ISSUE TITLE
Mac pkg installer icon

### ISSUE THREAD

**Issue by adrionics** [Santulator/Santulator#16]
I want to say a HUGE thank you for this whole project that has me diving in the deep end like a pro.

As a small way to say thanks, here is the solution to the icon in the pkg installer for mac.

To get your custom icon to show in the macos installer, all you need to do is add a set of folders to the root of the "package" project called "package/macosx" with an image called Santulator-background.png. 

<img width="300" alt="Screen Shot 2019-07-18 at 3 43 35 PM" src="https://user-images.githubusercontent.com/14155780/61494229-d962af80-a972-11e9-98bb-acfdb85c6146.png">

Here is the image I modified for that purpose.

![image](https://user-images.githubusercontent.com/14155780/61493981-33af4080-a972-11e9-8b07-b4502089884c.png)

Result:

<img width="617" alt="Screen Shot 2019-07-18 at 3 46 15 PM" src="https://user-images.githubusercontent.com/14155780/61494369-3a8a8300-a973-11e9-8b93-97d974873370.png">

Enjoy!

**Comment by AdamCarroll** [comment]
Hi @adrionics thanks for your kind words about the project!

And thanks for your suggestion, that looks like the solution to the problem, both here in Santulator and in [VocabHunter[https://github.com/VocabHunter/VocabHunter]

**Comment by adrionics** [comment]
I am not sure what the rules are. I found an image in the temp package folder that gradle tells you about and copied that size. The folder is in the last line of the console when running createPackage on MAC, for example:

`Config files are saved to /var/folders/wh/qghmj65j29v2wpq2731rxspm0000gn/T/jdk.packager17150472450090462369/macosx. Use them to customize package.`

There is more info on what can be customized when running the packager with --debug option. That is what gave me the clues on where to place the file. It was a bit of trial and error.

**Comment by AdamCarroll** [comment]
OK, no problem. I'm very glad of the help to cross off another problem from my list.  Thanks!

Here's the commit, based on a 200x200px file with a 150x150px central image: 86e739d79464e6dc205e1192813521f314f5d72b

**Comment by AdamCarroll** [comment]
I've just released v1.2.0 of Santulator that includes this fix.  I've added a reference to it in the [release notes](https://vocabhunter.github.io/2019/12/04/santulator-v1.2.0-released.html).
