### ISSUE TITLE
CFBundleVersion cannot be zero or negative

### ISSUE THREAD

**Issue by gernotstarke** [Santulator/Santulator#17]
I updated the javaFX module path for my (Mac) setup,
but cannot get past the following error:

```
Task :package:createBundle FAILED
The first number in a CFBundleVersion cannot be zero or negative.

```

I tried to pass command-line arguments (mac.CFBundleIdentifier or CFBundleVersion, but that didn't help either.

any idea?

Environment:

`$ java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)`

gradle 5.5

**Comment by AdamCarroll** [comment]
I think you've accidentally added this issue to the wrong project.  It doesn't sound like it's related to Santulator.  Have a check and if it's not for this project, let's close the issue.

If you're intereested in building the Santulator package, see the instructions in [PACKAGING.md](https://github.com/Santulator/Santulator/blob/master/package/PACKAGING.md)
